### ISSUE TITLE
Autoload en modo NO MMU

### ISSUE THREAD

**Issue by Dainse** [ComunidadMaker3D/CM3D-Prusa-Firmware#2]
Sería conveniente desactivar el autolad en el modo no MMU debido a la diferente funcionalidad mecánica que tiene el sensor cuando se usa MMU o no.

**Comment by jfestrada** [comment]
Se ha añadido la opción

`static void lcd_switch_mmu_status(){
	if(mmu_enabled){
		mmu_enabled=false;
		fsensor_autoload_set(false);
	}else{
		mmu_enabled=true;
	}
	fSetMmuMode(mmu_enabled);
}
`
